image: node:latest

pipelines:
  default:
    - step:
        script:
          - echo ""

  branches:
    SIT:
      - step:
          name : Deploy
          deployment: test
          script:
            - echo "Deployment Starting"
            - scp -o StrictHostKeyChecking=no ./deploy.sh ubuntu@172.172.160.6:~/deploy.sh
            - ssh -tt -o StrictHostKeyChecking=no ubuntu@172.172.160.6 "bash ~/deploy.sh"
            - echo "Deploying finished"
